import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
            <Image
              src="/images/SIGERTRIP.png"
              alt="Logo SigerTrip"
              width={130}
              height={40}
              className="object-contain"
            />
        </header>
        
        {/* panggil fungsi komponennavbar (menu) */}
        <menu />

        <main className="content">
          {children}
        </main>
        <footer>
          Copyright &copy; 2026 -  SigerTrip. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
